ps <- read.table("data/point_stage.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s <- read.table("data/stages.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
cam <- read.table("data/camino.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s1 <- read.table("data/stage1.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s2 <- read.table("data/stage2.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s3 <- read.table("data/stage3.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s4 <- read.table("data/stage4.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s5 <- read.table("data/stage5.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s6 <- read.table("data/stage6.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s7 <- read.table("data/stage7.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s8 <- read.table("data/stage8.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s9 <- read.table("data/stage9.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s10 <- read.table("data/stage10.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s11 <- read.table("data/stage11.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s12 <- read.table("data/stage12.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s13 <- read.table("data/stage13.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s14 <- read.table("data/stage14.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s15 <- read.table("data/stage15.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s16 <- read.table("data/stage16.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s17 <- read.table("data/stage17.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s18a <- read.table("data/stage18a.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s18b <- read.table("data/stage18b.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s19 <- read.table("data/stage19.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s20 <- read.table("data/stage20.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s21 <- read.table("data/stage21.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s22a <- read.table("data/stage22a.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s22b <- read.table("data/stage22b.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s23a <- read.table("data/stage23a.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s23b <- read.table("data/stage23b.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s24 <- read.table("data/stage24.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s25 <- read.table("data/stage25.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s26 <- read.table("data/stage26.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s27a <- read.table("data/stage27a.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s27b <- read.table("data/stage27b.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s28a <- read.table("data/stage28a.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s28b <- read.table("data/stage28b.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s29 <- read.table("data/stage29.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s30 <- read.table("data/stage30.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s31 <- read.table("data/stage31.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s32 <- read.table("data/stage32.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)
s33 <- read.table("data/stage33.csv", sep=",",header=TRUE,stringsAsFactors=FALSE)








